apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: raki
  labels:
    app: payment-service
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: raki
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgrespassword
