apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: raki
  labels:
    app: backend
type: Opaque
stringData:
  DB_NAME: my_database_name
  DB_USER: my_user
  DB_PASSWORD: my_password
  SECRET_KEY: "django-insecure-th-%d0roim2x$t-+inu!(v_eav@635=c30k*-=igvm$-uq_8jy"
  INTERNAL_API_TOKEN: "dev-secret-internal-token"
  R2_ACCESS_KEY_ID: "3184a13d63dcbdef4fa0e3885e672a22"
  R2_SECRET_ACCESS_KEY: "a86c79987e4b000b78439797ea5ecfc24856a78741781c23e94f764e44c6efb4"
