apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: raki

type: Opaque

stringData:
  DB_NAME: your_db

  DB_USER: postgres

  DB_PASSWORD: password

  SECRET_KEY: your-secret-key
