--
-- PostgreSQL database dump
--

\restrict tIMgSkzBObQtZfyCJOpuAcZEjImVEA0taS4OkXoTYVeHle5EDeVX20HfbC0N673

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.accounts_profile (
    id bigint NOT NULL,
    phone character varying(15),
    total_learned_cards integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_profile OWNER TO my_user;

--
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO my_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO my_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO my_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO my_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO my_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO my_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: card_card; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.card_card (
    id bigint NOT NULL,
    cloze_index integer NOT NULL,
    note_id bigint NOT NULL,
    template_id bigint NOT NULL
);


ALTER TABLE public.card_card OWNER TO my_user;

--
-- Name: card_card_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.card_card ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: card_progress; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.card_progress (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    "interval" integer NOT NULL,
    repetition integer NOT NULL,
    easiness double precision NOT NULL,
    next_review date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    card_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.card_progress OWNER TO my_user;

--
-- Name: card_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.card_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deck_deck; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.deck_deck (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_public boolean NOT NULL,
    parent_id bigint
);


ALTER TABLE public.deck_deck OWNER TO my_user;

--
-- Name: deck_deck_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.deck_deck ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deck_deck_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deck_userdeck; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.deck_userdeck (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    deck_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.deck_userdeck OWNER TO my_user;

--
-- Name: deck_userdeck_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.deck_userdeck ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deck_userdeck_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO my_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO my_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO my_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO my_user;

--
-- Name: note_fielddefinition; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.note_fielddefinition (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    note_type_id bigint NOT NULL
);


ALTER TABLE public.note_fielddefinition OWNER TO my_user;

--
-- Name: note_fielddefinition_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.note_fielddefinition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_fielddefinition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note_fieldvalue; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.note_fieldvalue (
    id bigint NOT NULL,
    value text NOT NULL,
    definition_id bigint NOT NULL,
    note_id bigint NOT NULL
);


ALTER TABLE public.note_fieldvalue OWNER TO my_user;

--
-- Name: note_fieldvalue_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.note_fieldvalue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_fieldvalue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note_note; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.note_note (
    id bigint NOT NULL,
    deck_id bigint NOT NULL,
    note_type_id bigint NOT NULL
);


ALTER TABLE public.note_note OWNER TO my_user;

--
-- Name: note_note_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.note_note ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note_notetype; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.note_notetype (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    user_id integer
);


ALTER TABLE public.note_notetype OWNER TO my_user;

--
-- Name: note_notetype_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.note_notetype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_notetype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note_template; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.note_template (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    front text NOT NULL,
    back text NOT NULL,
    note_type_id bigint NOT NULL
);


ALTER TABLE public.note_template OWNER TO my_user;

--
-- Name: note_template_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.note_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO my_user;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id integer,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO my_user;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_profile; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.accounts_profile (id, phone, total_learned_cards, user_id) FROM stdin;
1		3	1
2	0325287373	1	2
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Blacklisted Token	7	add_blacklistedtoken
26	Can change Blacklisted Token	7	change_blacklistedtoken
27	Can delete Blacklisted Token	7	delete_blacklistedtoken
28	Can view Blacklisted Token	7	view_blacklistedtoken
29	Can add Outstanding Token	8	add_outstandingtoken
30	Can change Outstanding Token	8	change_outstandingtoken
31	Can delete Outstanding Token	8	delete_outstandingtoken
32	Can view Outstanding Token	8	view_outstandingtoken
33	Can add profile	9	add_profile
34	Can change profile	9	change_profile
35	Can delete profile	9	delete_profile
36	Can view profile	9	view_profile
37	Can add deck	10	add_deck
38	Can change deck	10	change_deck
39	Can delete deck	10	delete_deck
40	Can view deck	10	view_deck
41	Can add user deck	11	add_userdeck
42	Can change user deck	11	change_userdeck
43	Can delete user deck	11	delete_userdeck
44	Can view user deck	11	view_userdeck
45	Can add field definition	12	add_fielddefinition
46	Can change field definition	12	change_fielddefinition
47	Can delete field definition	12	delete_fielddefinition
48	Can view field definition	12	view_fielddefinition
49	Can add note type	15	add_notetype
50	Can change note type	15	change_notetype
51	Can delete note type	15	delete_notetype
52	Can view note type	15	view_notetype
53	Can add template	16	add_template
54	Can change template	16	change_template
55	Can delete template	16	delete_template
56	Can view template	16	view_template
57	Can add note	14	add_note
58	Can change note	14	change_note
59	Can delete note	14	delete_note
60	Can view note	14	view_note
61	Can add field value	13	add_fieldvalue
62	Can change field value	13	change_fieldvalue
63	Can delete field value	13	delete_fieldvalue
64	Can view field value	13	view_fieldvalue
65	Can add card	17	add_card
66	Can change card	17	change_card
67	Can delete card	17	delete_card
68	Can view card	17	view_card
69	Can add progress	18	add_progress
70	Can change progress	18	change_progress
71	Can delete progress	18	delete_progress
72	Can view progress	18	view_progress
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$il7FjMVGQDggx6aetqeHjt$o3OSSMEy+DGHSpkDr+nrqhVFIKDfCHvDFPNF96240f0=	\N	f	user1	Quyên	Lệ	quyenhl@rabiloo.com	f	t	2026-06-04 09:13:56.010927+00
2	pbkdf2_sha256$1200000$D4QSmefbz47mBshAeGYnBa$n6tQl7nbWnChOF6UMpFRMLUckd9RxJlf/LXMq1GR8i4=	\N	f	duongtest	Dương	Thùy	duongntt@rabiloo.com	f	t	2026-06-04 09:14:39.081978+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: card_card; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.card_card (id, cloze_index, note_id, template_id) FROM stdin;
1	0	1	1
2	0	2	6
3	0	2	7
4	1	2	8
5	0	3	1
6	0	4	1
7	0	5	1
8	0	6	1
9	0	7	1
10	0	8	1
11	0	9	1
12	0	10	1
13	0	11	1
14	0	12	1
15	0	13	2
16	0	13	3
17	0	14	6
18	0	14	7
19	1	14	8
20	0	15	6
21	0	15	7
22	1	15	8
23	0	16	6
24	0	16	7
25	1	16	8
\.


--
-- Data for Name: card_progress; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.card_progress (id, status, "interval", repetition, easiness, next_review, created_at, card_id, user_id) FROM stdin;
1	review	1	0	2.5	2026-06-05	2026-06-04 09:16:54.285177+00	2	1
2	review	1	0	2.5	2026-06-05	2026-06-04 09:17:07.906427+00	3	1
3	review	1	0	2.5	2026-06-05	2026-06-04 09:17:09.83021+00	4	1
4	learning	0	0	2.5	2026-06-04	2026-06-04 09:25:06.963836+00	1	2
\.


--
-- Data for Name: deck_deck; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.deck_deck (id, name, description, created_at, is_public, parent_id) FROM stdin;
1	Quyên		2026-06-04 09:14:50.894937+00	f	\N
2	quyen	123456	2026-06-04 09:15:15.730096+00	t	\N
3	quyen		2026-06-04 09:24:30.378998+00	f	\N
4	Sub Deck		2026-06-04 09:24:35.032101+00	f	\N
5	Demo		2026-06-04 09:24:37.506757+00	f	\N
7	Demo		2026-06-04 09:24:43.082717+00	f	\N
8	7/5		2026-06-04 09:24:45.761592+00	f	\N
9	7/5		2026-06-04 09:24:48.49468+00	f	\N
10	Demo		2026-06-04 09:24:51.132196+00	f	\N
11	Demo		2026-06-04 09:24:53.355518+00	f	\N
6	1	là gì	2026-06-04 09:24:40.421635+00	f	\N
\.


--
-- Data for Name: deck_userdeck; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.deck_userdeck (id, role, deck_id, user_id) FROM stdin;
1	owner	1	2
2	owner	2	1
3	owner	3	1
4	owner	4	1
5	owner	5	1
6	owner	6	1
7	owner	7	1
8	owner	8	1
9	owner	9	1
10	owner	10	1
11	owner	11	1
12	viewer	2	2
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	token_blacklist	blacklistedtoken
8	token_blacklist	outstandingtoken
9	accounts	profile
10	deck	deck
11	deck	userdeck
12	note	fielddefinition
13	note	fieldvalue
14	note	note
15	note	notetype
16	note	template
17	card	card
18	card	progress
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-06-04 09:13:37.268009+00
2	auth	0001_initial	2026-06-04 09:13:37.371389+00
3	accounts	0001_initial	2026-06-04 09:13:37.408024+00
4	admin	0001_initial	2026-06-04 09:13:37.462684+00
5	admin	0002_logentry_remove_auto_add	2026-06-04 09:13:37.485179+00
6	admin	0003_logentry_add_action_flag_choices	2026-06-04 09:13:37.514163+00
7	contenttypes	0002_remove_content_type_name	2026-06-04 09:13:37.566963+00
8	auth	0002_alter_permission_name_max_length	2026-06-04 09:13:37.600665+00
9	auth	0003_alter_user_email_max_length	2026-06-04 09:13:37.635471+00
10	auth	0004_alter_user_username_opts	2026-06-04 09:13:37.667052+00
11	auth	0005_alter_user_last_login_null	2026-06-04 09:13:37.698742+00
12	auth	0006_require_contenttypes_0002	2026-06-04 09:13:37.703024+00
13	auth	0007_alter_validators_add_error_messages	2026-06-04 09:13:37.735576+00
14	auth	0008_alter_user_username_max_length	2026-06-04 09:13:37.779551+00
15	auth	0009_alter_user_last_name_max_length	2026-06-04 09:13:37.804774+00
16	auth	0010_alter_group_name_max_length	2026-06-04 09:13:37.837044+00
17	auth	0011_update_proxy_permissions	2026-06-04 09:13:37.858925+00
18	auth	0012_alter_user_first_name_max_length	2026-06-04 09:13:37.883591+00
19	deck	0001_initial	2026-06-04 09:13:37.968844+00
20	note	0001_initial	2026-06-04 09:13:38.183565+00
21	note	0002_auto_20260504_0902	2026-06-04 09:13:38.302083+00
22	card	0001_initial	2026-06-04 09:13:38.401155+00
23	deck	0002_alter_userdeck_role	2026-06-04 09:13:38.428248+00
24	sessions	0001_initial	2026-06-04 09:13:38.457685+00
25	token_blacklist	0001_initial	2026-06-04 09:13:38.590065+00
26	token_blacklist	0002_outstandingtoken_jti_hex	2026-06-04 09:13:38.621161+00
27	token_blacklist	0003_auto_20171017_2007	2026-06-04 09:13:38.67364+00
28	token_blacklist	0004_auto_20171017_2013	2026-06-04 09:13:38.718549+00
29	token_blacklist	0005_remove_outstandingtoken_jti	2026-06-04 09:13:38.748973+00
30	token_blacklist	0006_auto_20171017_2113	2026-06-04 09:13:38.783702+00
31	token_blacklist	0007_auto_20171017_2214	2026-06-04 09:13:38.891756+00
32	token_blacklist	0008_migrate_to_bigautofield	2026-06-04 09:13:39.018014+00
33	token_blacklist	0010_fix_migrate_to_bigautofield	2026-06-04 09:13:39.066373+00
34	token_blacklist	0011_linearizes_history	2026-06-04 09:13:39.069537+00
35	token_blacklist	0012_alter_outstandingtoken_user	2026-06-04 09:13:39.104093+00
36	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2026-06-04 09:13:39.141952+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: note_fielddefinition; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.note_fielddefinition (id, name, note_type_id) FROM stdin;
1	Front	1
2	Back	1
3	Front	2
4	Back	2
5	Text	3
6	Front	4
7	Back	4
8	1	5
9	2	5
10	3	5
11	4	5
\.


--
-- Data for Name: note_fieldvalue; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.note_fieldvalue (id, value, definition_id, note_id) FROM stdin;
1	hello	1	1
2	me	2	1
3	nhất	8	2
4	nhị	9	2
5	tam	10	2
6	4	11	2
7	me	1	3
8	toi	2	3
9	ban	1	4
10	you	2	4
11	q	1	5
12	w	2	5
13	1	1	6
14	mot	2	6
15	2	1	7
16	hai	2	7
17	4	1	8
18	bon	2	8
19	5	1	9
20	nam	2	9
21	em	1	10
22	me	2	10
23	reu	1	11
24	mue	2	11
25	a	1	12
26	a	2	12
27	a	3	13
28	a	4	13
29	a	8	14
30	a	9	14
31	a	10	14
32	a	11	14
33	a	8	15
34	a	9	15
35	a	10	15
36	a	11	15
37	a	8	16
38	a	9	16
39	a	10	16
40	a	11	16
\.


--
-- Data for Name: note_note; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.note_note (id, deck_id, note_type_id) FROM stdin;
1	1	1
2	2	5
3	1	1
4	1	1
5	1	1
6	1	1
7	1	1
8	1	1
9	1	1
10	1	1
11	1	1
12	1	1
13	11	2
14	11	5
15	11	5
16	11	5
\.


--
-- Data for Name: note_notetype; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.note_notetype (id, name, user_id) FROM stdin;
1	Basic	\N
2	Basic (And Reversed Card)	\N
3	Cloze	\N
4	Basic (type in the answer)	\N
5	học tiếng anh	1
\.


--
-- Data for Name: note_template; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.note_template (id, name, front, back, note_type_id) FROM stdin;
1	Card 1	{{Front}}	{{Back}}	1
2	Card 1	{{Front}}	{{Back}}	2
3	Card 2	{{Back}}	{{Front}}	2
4	Cloze Card	{{c1::Text}}	{{Text}}	3
5	Card 1	{{Front}}	{{Front}}<hr id='answer'>{{type:Back}}	4
6	1	nhất	{{1}}	5
7	2	nhị	{{type:2}}	5
8	3	<!--CLOZE_TEMPLATE-->{{3}} và {{c1::{{3}}}}	{{3}} và {{c1::{{3}}}}	5
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2026-06-04 09:59:47.88979+00	3
2	2026-06-04 09:59:51.807708+00	5
3	2026-06-05 01:48:54.717235+00	8
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTE2OTI4NSwiaWF0IjoxNzgwNTY0NDg1LCJqdGkiOiJkOWY4ODJhMmYzZWI0MzY4YmE0NDE4MTFkYjQ4MDVjNSIsInVzZXJfaWQiOiIxIn0.YVzxtBz375QPPuv5BNL7Wfew9OkBxo9Jw-Rhy9tuW7o	2026-06-04 09:14:45.082181+00	2026-06-11 09:14:45+00	1	d9f882a2f3eb4368ba441811db4805c5
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTE2OTI4NSwiaWF0IjoxNzgwNTY0NDg1LCJqdGkiOiI1ODhmOGEwZjdkNDg0NDUzYjUyZDdkYTI1MzA3MDNhOCIsInVzZXJfaWQiOiIyIn0.bdAOkfKmBLTAO1-7QaNJJP8-GTsW0-3WN1H8Hpdu-yI	2026-06-04 09:14:45.130919+00	2026-06-11 09:14:45+00	2	588f8a0f7d484453b52d7da2530703a8
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTE2OTMwOCwiaWF0IjoxNzgwNTY0NTA4LCJqdGkiOiJkZDBmNWI3NjJiNDQ0ZGYxOWQ3MjQ0ZjJjNmM0Njc0MyIsInVzZXJfaWQiOiIxIn0.9ywMRZWc0QsMoHVsYjGaJ59-KfrmepDYcak-JgsGBUM	2026-06-04 09:15:08.69419+00	2026-06-11 09:15:08+00	1	dd0f5b762b444df19d7244f2c6c46743
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTE3MTk4NywiaWF0IjoxNzgwNTY3MTg3LCJqdGkiOiJlZGI4YWQ5ODZjY2I0MDdkOWQ5ZThlMDE1ZGQ1ZjBlMCIsInVzZXJfaWQiOiIxIn0.PiOtKIWfGrFk8q4m5sRlI4x-GVtqPPFGeD20IGT9BY4	2026-06-04 09:59:47.80469+00	2026-06-11 09:59:47+00	1	edb8ad986ccb407d9d9e8e015dd5f0e0
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTE2ODk3NiwiaWF0IjoxNzgwNTY0MTc2LCJqdGkiOiJiMDQxODEzODUzNDQ0NjJkOWJkMmExNDNhZDNiZjFiMiIsInVzZXJfaWQiOiIxIn0.FhGyUhsu8PSuTJx_rJs2XMS3uKfqrVJq4kcGOjddmIs	2026-06-04 09:59:51.686791+00	2026-06-11 09:09:36+00	1	b04181385344462d9bd2a143ad3bf1b2
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTE3MTk5MSwiaWF0IjoxNzgwNTY3MTkxLCJqdGkiOiIwNWY2OGZhYWQyMjg0MzY0YTgwMmJhYjBhM2IxNGU5NCIsInVzZXJfaWQiOiIxIn0.Mj5t6yaUbNrNmFNkix_VqvKr80V0ZZYzo92Q6jtE0mA	2026-06-04 09:59:51.686791+00	2026-06-11 09:59:51+00	1	05f68faad2284364a802bab0a3b14e94
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTE3MTk5NywiaWF0IjoxNzgwNTY3MTk3LCJqdGkiOiJkZGQ2ODYxMzhlODQ0YzNmYThjN2VmZDJhODdmMjkyMyIsInVzZXJfaWQiOiIxIn0.LoQCqZH8IDFb_dmpF8NFun3K4HNBkva7FZa8I-6RLMI	2026-06-04 09:59:57.920545+00	2026-06-11 09:59:57+00	1	ddd686138e844c3fa8c7efd2a87f2923
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTE3MjYxOSwiaWF0IjoxNzgwNTY3ODE5LCJqdGkiOiIyOTYyMjQ3NzM5NmE0YTBlODI4NWE1NTlkNjE3MGMzMiIsInVzZXJfaWQiOiIxIn0.DZ6d7L89WBv2gyHKujcF2aylAJ52aUIkIHd25THDdBM	2026-06-04 10:10:19.693656+00	2026-06-11 10:10:19+00	1	29622477396a4a0e8285a559d6170c32
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTIyODkzNCwiaWF0IjoxNzgwNjI0MTM0LCJqdGkiOiI0NGNjODk0MzgxMGU0OGY0YmQ1ZTUzYjIyN2NkZDhjNCIsInVzZXJfaWQiOiIxIn0.KRg2OLedQHiRcOh4QAQOihFkVVJYRsQTnWgpdQFuOLU	2026-06-05 01:48:54.667381+00	2026-06-12 01:48:54+00	1	44cc8943810e48f4bd5e53b227cdd8c4
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTIyODk0MywiaWF0IjoxNzgwNjI0MTQzLCJqdGkiOiIzMzQ0YTI0NmFjZDQ0NWUzYTliNjJlZTZjMGJiMzI3MiIsInVzZXJfaWQiOiIxIn0.3CmgdBYfiIEm5LIuG1_DWSQBKT5n20STUU33VpiCM6o	2026-06-05 01:49:03.452702+00	2026-06-12 01:49:03+00	1	3344a246acd445e3a9b62ee6c0bb3272
\.


--
-- Name: accounts_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.accounts_profile_id_seq', 2, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: card_card_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.card_card_id_seq', 25, true);


--
-- Name: card_progress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.card_progress_id_seq', 4, true);


--
-- Name: deck_deck_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.deck_deck_id_seq', 11, true);


--
-- Name: deck_userdeck_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.deck_userdeck_id_seq', 12, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 36, true);


--
-- Name: note_fielddefinition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.note_fielddefinition_id_seq', 11, true);


--
-- Name: note_fieldvalue_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.note_fieldvalue_id_seq', 40, true);


--
-- Name: note_note_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.note_note_id_seq', 16, true);


--
-- Name: note_notetype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.note_notetype_id_seq', 5, true);


--
-- Name: note_template_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.note_template_id_seq', 8, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 3, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 10, true);


--
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: card_card card_card_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.card_card
    ADD CONSTRAINT card_card_pkey PRIMARY KEY (id);


--
-- Name: card_progress card_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.card_progress
    ADD CONSTRAINT card_progress_pkey PRIMARY KEY (id);


--
-- Name: card_progress card_progress_user_id_card_id_831e4ac0_uniq; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.card_progress
    ADD CONSTRAINT card_progress_user_id_card_id_831e4ac0_uniq UNIQUE (user_id, card_id);


--
-- Name: deck_deck deck_deck_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.deck_deck
    ADD CONSTRAINT deck_deck_pkey PRIMARY KEY (id);


--
-- Name: deck_userdeck deck_userdeck_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.deck_userdeck
    ADD CONSTRAINT deck_userdeck_pkey PRIMARY KEY (id);


--
-- Name: deck_userdeck deck_userdeck_user_id_deck_id_cccda29f_uniq; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.deck_userdeck
    ADD CONSTRAINT deck_userdeck_user_id_deck_id_cccda29f_uniq UNIQUE (user_id, deck_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: note_fielddefinition note_fielddefinition_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_fielddefinition
    ADD CONSTRAINT note_fielddefinition_pkey PRIMARY KEY (id);


--
-- Name: note_fieldvalue note_fieldvalue_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_fieldvalue
    ADD CONSTRAINT note_fieldvalue_pkey PRIMARY KEY (id);


--
-- Name: note_note note_note_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_note
    ADD CONSTRAINT note_note_pkey PRIMARY KEY (id);


--
-- Name: note_notetype note_notetype_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_notetype
    ADD CONSTRAINT note_notetype_pkey PRIMARY KEY (id);


--
-- Name: note_template note_template_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_template
    ADD CONSTRAINT note_template_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: card_card_note_id_bc1cbf4f; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX card_card_note_id_bc1cbf4f ON public.card_card USING btree (note_id);


--
-- Name: card_card_template_id_d35b43eb; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX card_card_template_id_d35b43eb ON public.card_card USING btree (template_id);


--
-- Name: card_progress_card_id_1472d169; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX card_progress_card_id_1472d169 ON public.card_progress USING btree (card_id);


--
-- Name: card_progress_user_id_4b00ebad; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX card_progress_user_id_4b00ebad ON public.card_progress USING btree (user_id);


--
-- Name: deck_deck_parent_id_2752ca5c; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX deck_deck_parent_id_2752ca5c ON public.deck_deck USING btree (parent_id);


--
-- Name: deck_userdeck_deck_id_8be29f82; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX deck_userdeck_deck_id_8be29f82 ON public.deck_userdeck USING btree (deck_id);


--
-- Name: deck_userdeck_user_id_b4c4289a; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX deck_userdeck_user_id_b4c4289a ON public.deck_userdeck USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: note_fielddefinition_note_type_id_02368220; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX note_fielddefinition_note_type_id_02368220 ON public.note_fielddefinition USING btree (note_type_id);


--
-- Name: note_fieldvalue_definition_id_1ac17edc; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX note_fieldvalue_definition_id_1ac17edc ON public.note_fieldvalue USING btree (definition_id);


--
-- Name: note_fieldvalue_note_id_44b75090; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX note_fieldvalue_note_id_44b75090 ON public.note_fieldvalue USING btree (note_id);


--
-- Name: note_note_deck_id_f8e7410f; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX note_note_deck_id_f8e7410f ON public.note_note USING btree (deck_id);


--
-- Name: note_note_note_type_id_4e86d1ef; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX note_note_note_type_id_4e86d1ef ON public.note_note USING btree (note_type_id);


--
-- Name: note_notetype_user_id_d781dc0f; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX note_notetype_user_id_d781dc0f ON public.note_notetype USING btree (user_id);


--
-- Name: note_template_note_type_id_10906c96; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX note_template_note_type_id_10906c96 ON public.note_template USING btree (note_type_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: my_user
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: accounts_profile accounts_profile_user_id_49a85d32_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_49a85d32_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: card_card card_card_note_id_bc1cbf4f_fk_note_note_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.card_card
    ADD CONSTRAINT card_card_note_id_bc1cbf4f_fk_note_note_id FOREIGN KEY (note_id) REFERENCES public.note_note(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: card_card card_card_template_id_d35b43eb_fk_note_template_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.card_card
    ADD CONSTRAINT card_card_template_id_d35b43eb_fk_note_template_id FOREIGN KEY (template_id) REFERENCES public.note_template(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: card_progress card_progress_card_id_1472d169_fk_card_card_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.card_progress
    ADD CONSTRAINT card_progress_card_id_1472d169_fk_card_card_id FOREIGN KEY (card_id) REFERENCES public.card_card(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: card_progress card_progress_user_id_4b00ebad_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.card_progress
    ADD CONSTRAINT card_progress_user_id_4b00ebad_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: deck_deck deck_deck_parent_id_2752ca5c_fk_deck_deck_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.deck_deck
    ADD CONSTRAINT deck_deck_parent_id_2752ca5c_fk_deck_deck_id FOREIGN KEY (parent_id) REFERENCES public.deck_deck(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: deck_userdeck deck_userdeck_deck_id_8be29f82_fk_deck_deck_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.deck_userdeck
    ADD CONSTRAINT deck_userdeck_deck_id_8be29f82_fk_deck_deck_id FOREIGN KEY (deck_id) REFERENCES public.deck_deck(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: deck_userdeck deck_userdeck_user_id_b4c4289a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.deck_userdeck
    ADD CONSTRAINT deck_userdeck_user_id_b4c4289a_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: note_fielddefinition note_fielddefinition_note_type_id_02368220_fk_note_notetype_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_fielddefinition
    ADD CONSTRAINT note_fielddefinition_note_type_id_02368220_fk_note_notetype_id FOREIGN KEY (note_type_id) REFERENCES public.note_notetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: note_fieldvalue note_fieldvalue_definition_id_1ac17edc_fk_note_fiel; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_fieldvalue
    ADD CONSTRAINT note_fieldvalue_definition_id_1ac17edc_fk_note_fiel FOREIGN KEY (definition_id) REFERENCES public.note_fielddefinition(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: note_fieldvalue note_fieldvalue_note_id_44b75090_fk_note_note_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_fieldvalue
    ADD CONSTRAINT note_fieldvalue_note_id_44b75090_fk_note_note_id FOREIGN KEY (note_id) REFERENCES public.note_note(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: note_note note_note_deck_id_f8e7410f_fk_deck_deck_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_note
    ADD CONSTRAINT note_note_deck_id_f8e7410f_fk_deck_deck_id FOREIGN KEY (deck_id) REFERENCES public.deck_deck(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: note_note note_note_note_type_id_4e86d1ef_fk_note_notetype_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_note
    ADD CONSTRAINT note_note_note_type_id_4e86d1ef_fk_note_notetype_id FOREIGN KEY (note_type_id) REFERENCES public.note_notetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: note_notetype note_notetype_user_id_d781dc0f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_notetype
    ADD CONSTRAINT note_notetype_user_id_d781dc0f_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: note_template note_template_note_type_id_10906c96_fk_note_notetype_id; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.note_template
    ADD CONSTRAINT note_template_note_type_id_10906c96_fk_note_notetype_id FOREIGN KEY (note_type_id) REFERENCES public.note_notetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict tIMgSkzBObQtZfyCJOpuAcZEjImVEA0taS4OkXoTYVeHle5EDeVX20HfbC0N673

