
services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  backend:
    image: 103487/raki-backend:v3.0
    build: ./raki
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    command: >
      sh -c "until python -c 'import socket; s = socket.socket(); s.connect((\"db\", 5432))' 2>/dev/null; do 
               echo 'Đang chờ Database khởi động...'; 
               sleep 1; 
             done;
             echo 'Database đã sẵn sàng! Bắt đầu migrate...';
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"


  # Giữ nguyên db, web, frontend ở trên...
  
  # Thêm service này vào dưới cùng của file:
  raki-page:
    build:
      context: ./raki-page  # Trỏ ra ngoài folder Next.js độc lập của bạn
      dockerfile: Dockerfile
    # Không cần ghi mục ports ở đây, vì ta sẽ cho Nginx ở bên frontend gọi nó nội bộ

  frontend:
    image: 103487/raki-frontend:v4.0
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

    env_file:
      - .env
volumes:
  postgres_data:

