# Generated by Django 6.0.5 on 2026-07-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_remove_deck_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='coin_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdeck',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=20),
        ),
    ]
