apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: raki
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: raki
data:
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://notification-db:5432/notification_db"
  SERVER_PORT: "8081"
