apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: raki
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: raki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: 103487/raki-notification-service:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: notification-config
            - secretRef:
                name: notification-secret
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
