apiVersion: v1
kind: Service
metadata:
  name: notification-db
  namespace: raki
  labels:
    app: notification-db
    app.kubernetes.io/name: notification-db
    app.kubernetes.io/part-of: raki
spec:
  type: ClusterIP
  selector:
    app: notification-db
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
