apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: raki
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: raki
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
