spring.application.name=payment_service

# Database Configuration
spring.datasource.url=jdbc:postgresql://raki-postgres:5432/raki_db
spring.datasource.username=postgres
spring.datasource.password=postgres 

pring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
