"""empty message

Revision ID: 643946dbed15
Revises: eba6e4d63bcc
Create Date: 2026-07-09 04:21:33.289112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '643946dbed15'
down_revision: Union[str, Sequence[str], None] = 'eba6e4d63bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_message_read_user_id'), table_name='message_read')
    op.drop_index(op.f('ix_message_read_id'), table_name='message_read')
    op.drop_table('message_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_read',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('message_read_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_read_pkey'))
    )
    op.create_index(op.f('ix_message_read_id'), 'message_read', ['id'], unique=False)
    op.create_index(op.f('idx_message_read_user_id'), 'message_read', ['user_id'], unique=False)
    # ### end Alembic commands ###
