# Generated by Django 4.2.11 on 2026-05-04 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='note.note')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='note.template')),
            ],
        ),
    ]
