# Generated by Django 4.2.11 on 2026-04-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review', models.DateTimeField(db_index=True)),
                ('easiness', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=0)),
                ('repetition', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='note.note')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='note.template')),
            ],
        ),
    ]
