# Generated by Django 4.2.11 on 2026-04-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='easiness',
        ),
        migrations.RemoveField(
            model_name='card',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='card',
            name='next_review',
        ),
        migrations.RemoveField(
            model_name='card',
            name='repetition',
        ),
    ]
