# Generated by Django 4.2.11 on 2026-04-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_card_created_at_remove_card_easiness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='template_id',
            new_name='template',
        ),
    ]
