apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
  namespace: raki
  labels:
    app: chat-service
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/part-of: raki
type: Opaque
stringData:
  CHAT_DB_NAME: chat_db
  CHAT_DB_USER: chat_user
  CHAT_DB_PASSWORD: "123456"
  SECRET_KEY: "django-insecure-th-%d0roim2x$t-+inu!(v_eav@635=c30k*-=igvm$-uq_8jy"
  INTERNAL_API_TOKEN: "dev-secret-internal-token"
  R2_ACCESS_KEY_ID: "3184a13d63dcbdef4fa0e3885e672a22"
  R2_SECRET_ACCESS_KEY: "a86c79987e4b000b78439797ea5ecfc24856a78741781c23e94f764e44c6efb4"
