apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: raki
  labels:
    app: chat-service
spec:
  type: ClusterIP
  selector:
    app: chat-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
