import json
import uuid
import requests
import hmac
import hashlib
from django.conf import settings

# MoMo payment helper
# This function creates a MoMo payment request and returns the payment URL.
def create_momo_payment(amount, redirect_url, ipn_url, order_id):
    """Create a MoMo payment request and return the payment URL.

    The *order_id* is generated by the caller (usually includes the internal
    ``payment_history.id``) so that the callback can be matched to the DB record.
    """
    # Configuration – test keys (move to settings for production)
    endpoint = "https://test-payment.momo.vn/v2/gateway/api/create"
    access_key = "F8BBA842ECF85"
    secret_key = "K951B6PE1waDMi640xX08PD3vg6EkVlz"
    partner_code = "MOMO"
    partner_name = "MoMo Payment"
    request_type = "payWithMethod"
    store_id = "Test Store"
    order_info = "pay with MoMo"
    lang = "vi"
    extra_data = ""
    auto_capture = True

    # MoMo requires a requestId – generate it here
    request_id = str(uuid.uuid4())

    raw_signature = (
        f"accessKey={access_key}&amount={amount}&extraData={extra_data}&ipnUrl={ipn_url}"
        f"&orderId={order_id}&orderInfo={order_info}&partnerCode={partner_code}"
        f"&redirectUrl={redirect_url}&requestId={request_id}&requestType={request_type}"
    )
    signature = hmac.new(secret_key.encode("ascii"), raw_signature.encode("ascii"), hashlib.sha256).hexdigest()

    data = {
        "partnerCode": partner_code,
        "orderId": order_id,
        "partnerName": partner_name,
        "storeId": store_id,
        "ipnUrl": ipn_url,
        "amount": str(amount),
        "lang": lang,
        "requestType": request_type,
        "redirectUrl": redirect_url,
        "autoCapture": auto_capture,
        "orderInfo": order_info,
        "requestId": request_id,
        "extraData": extra_data,
        "signature": signature,
        "orderGroupId": "",
    }

    payload = json.dumps(data)
    headers = {"Content-Type": "application/json", "Content-Length": str(len(payload))}
    response = requests.post(endpoint, data=payload, headers=headers)
    response.raise_for_status()
    resp_json = response.json()
    return resp_json.get("payUrl")
