# Generated by Django 4.2.11 on 2026-04-15 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deck', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='deck.deck')),
            ],
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('definition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='note.definition')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='note.note')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('note_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='note.notetype')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='note_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='note.notetype'),
        ),
        migrations.AddField(
            model_name='definition',
            name='note_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='note.notetype'),
        ),
    ]
