# Generated by Django 4.2.11 on 2026-05-04 09:02

from django.db import migrations


def create_default_notetypes(apps, schema_editor):
    NoteType = apps.get_model("note", "NoteType")
    FieldDefinition = apps.get_model("note", "FieldDefinition")
    Template = apps.get_model("note", "Template")

    # --- 1. LOẠI BASIC ---
    basic_nt, created = NoteType.objects.get_or_create(user=None, name="Basic")
    if created:
        FieldDefinition.objects.create(note_type=basic_nt, name="Front")
        FieldDefinition.objects.create(note_type=basic_nt, name="Back")
        Template.objects.create(
            note_type=basic_nt, name="Card 1", front="{{Front}}", back="{{Back}}"
        )

    # --- 2. LOẠI BASIC (CÓ ĐẢO NGƯỢC) ---
    reversed_nt, created = NoteType.objects.get_or_create(
        user=None, name="Basic (And Reversed Card)"
    )
    if created:
        FieldDefinition.objects.create(note_type=reversed_nt, name="Front")
        FieldDefinition.objects.create(note_type=reversed_nt, name="Back")
        Template.objects.create(
            note_type=reversed_nt, name="Card 1", front="{{Front}}", back="{{Back}}"
        )
        Template.objects.create(
            note_type=reversed_nt, name="Card 2", front="{{Back}}", back="{{Front}}"
        )


def create_cloze_notetype(apps, schema_editor):
    NoteType = apps.get_model("note", "NoteType")
    FieldDefinition = apps.get_model("note", "FieldDefinition")
    Template = apps.get_model("note", "Template")

    cloze_nt, created = NoteType.objects.get_or_create(user=None, name="Cloze")
    if created:
        FieldDefinition.objects.create(note_type=cloze_nt, name="Text")
        Template.objects.create(
            note_type=cloze_nt,
            name="Cloze Card",
            front="{{cloze:Text}}",
            back="{{Text}}",
        )


def create_type_answer_notetype(apps, schema_editor):
    NoteType = apps.get_model("note", "NoteType")
    FieldDefinition = apps.get_model("note", "FieldDefinition")
    Template = apps.get_model("note", "Template")

    type_nt, created = NoteType.objects.get_or_create(
        user=None, name="Basic (type in the answer)"
    )
    if created:
        FieldDefinition.objects.create(note_type=type_nt, name="Front")
        FieldDefinition.objects.create(note_type=type_nt, name="Back")

        Template.objects.create(
            note_type=type_nt,
            name="Card 1",
            front="{{Front}}<br><br>{{type:Back}}",
            back="{{Front}}<hr id='answer'>{{type:Back}}",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_notetypes),
        migrations.RunPython(create_cloze_notetype),
        migrations.RunPython(create_type_answer_notetype),
    ]
