# Generated by Django 4.2.11 on 2026-04-16 06:32

from django.db import migrations


def create_basic_notetype(apps, schema_editor):
    NoteType = apps.get_model("note", "NoteType")
    Definition = apps.get_model("note", "Definition")
    Template = apps.get_model("note", "Template")

    # user=None is correct for get_or_create when the field is nullable
    basic_nt, created = NoteType.objects.get_or_create(user=None, name="Basic")
    if created:
        def_front = Definition.objects.create(note_type_id=basic_nt, name="Front")
        def_back = Definition.objects.create(note_type_id=basic_nt, name="Back")
        Template.objects.create(
            note_type_id=basic_nt, name="Card 1", front="{{Front}}", back="{{Back}}"
        )
        Template.objects.create(
            note_type_id=basic_nt, name="Card 2", front="{{Back}}", back="{{Front}}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0002_alter_notetype_user"),
    ]

    operations = [
        migrations.RunPython(create_basic_notetype),
    ]
