# Generated by Django 4.2.11 on 2026-04-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20260416_0632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Definition',
            new_name='FieldDefinition',
        ),
        migrations.RenameModel(
            old_name='Value',
            new_name='FieldValue',
        ),
    ]
