# Generated by Django 4.2.11 on 2026-04-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_rename_definition_fielddefinition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fielddefinition',
            old_name='note_type_id',
            new_name='note_type',
        ),
        migrations.RenameField(
            model_name='fieldvalue',
            old_name='definition_id',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='fieldvalue',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='deck_id',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_type_id',
            new_name='note_type',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='note_type_id',
            new_name='note_type',
        ),
    ]
