apiVersion: v1
kind: Service
metadata:
  name: mail-service
  namespace: raki
  labels:
    app: mail-service
    app.kubernetes.io/name: mail-service
    app.kubernetes.io/part-of: raki
spec:
  type: ClusterIP
  selector:
    app: mail-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
