# Generated by Django 6.0.5 on 2026-07-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_simplify_coin_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinhistory',
            name='reference_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
