apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: raki
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          envFrom:
            - secretRef:
                name: rabbitmq-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            failureThreshold: 18
            periodSeconds: 10
            timeoutSeconds: 5

          # 2. LivenessProbe: Chỉ check sau khi startupProbe thành công
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 10 # Chỉ cần delay ngắn vì đã qua giai đoạn startup
            periodSeconds: 20 # Giãn thời gian kiểm tra ra (20s)
            timeoutSeconds: 10

          # 3. ReadinessProbe: Check xem đã sẵn sàng nhận traffic chưa
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
