apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: raki
  labels:
    app: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: raki
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
