# Generated by Django 4.2.11 on 2026-06-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeck',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
