# Generated by Django 4.2.11 on 2026-04-17 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.AddField(
            model_name='deck',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_users', to='deck.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'deck')},
            },
        ),
    ]
