# Generated by Django 4.2.11 on 2026-04-21 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review')], default='learning', max_length=20),
        ),
        migrations.AlterField(
            model_name='progress',
            name='interval',
            field=models.IntegerField(default=1),
        ),
    ]
