# Generated by Django 4.2.11 on 2026-04-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_created_at_progress_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='progress',
            name='next_review',
            field=models.DateField(),
        ),
    ]
