# Generated by Django 4.2.11 on 2026-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
