# Generated by Django 4.2.11 on 2026-04-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_last_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_review_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='streak',
        ),
    ]
