apiVersion: v1
kind: Service
metadata:
  name: raki-page
  namespace: raki
  labels:
    app: raki-page
    app.kubernetes.io/name: raki-page
    app.kubernetes.io/part-of: raki
spec:
  type: ClusterIP
  selector:
    app: raki-page
  ports:
    - name: http
      port: 3000
      targetPort: 3000
